version: "3.3"
services:
  db:
    image: postgres:12.1-alpine
    container_name: "hikaricpDemo-postgres"
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'